#!/bin/sh

#
# Installation script
#
# 1) cp tal_common.config.default tal_common.config
# 2) cp tal_regeneron.config.default tal_regeneron.config
# 3) cp tal_csd_ucd.config.default tal_csd_ucd.config
# 4) cp tal_csd_wtsi.config.default tal_csd_wtsi.config
# 5) cp tal_eucomm_wtsi.config.default tal_eucomm_wtsi.config
# 6) cp tal_eucomm_hgmu.config.default tal_eucomm_hgmu.config
# 7) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi


#
# Make sure config files exist
#
cd `dirname $0`

# establish the config files
REGENERON_CONFIG=tal_regeneron.config
CSD_WTSI_CONFIG-tal_csd_wtsi.config
CSD_UCD_CONFIG-tal_csd_ucd.config
EUCOMM_WTSI_CONFIG-tal_eucomm_wtsi.config
EUCOMM_HGMU_CONFIG-tal_eucomm_hgmu.config
COMMON_CONFIG=tal_common.config

# Make sure config file exists and source it
if [ -r ${REGENERON_CONFIG} ]
then
    echo "Source ${REGENERON_CONFIG}"
    . ${REGENERON_CONFIG}
else
    echo "Cannot source configuration file: ${REGENERON_CONFIG}"
    installFailed
fi

# Make sure config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi


#
# run DLAInstall for each configuration file
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

# Make sure config file exists and source it
if [ -r ${CSD_WTSI_CONFIG} ]
then
    echo "Source ${CSD_WTSI_CONFIG}"
    . ${CSD_WTSI_CONFIG}
else
    echo "Cannot source configuration file: ${CSD_WTSI_CONFIG}"
    installFailed
fi

#
# run DLAInstall for tal_csd_ucd
# source tal_common.config again
#
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV}


# Make sure config file exists and source it
if [ -r ${CSD_UCD_CONFIG} ]
then
    echo "Source ${CSD_UCD_CONFIG}"
    . ${CSD_UCD_CONFIG}
else
    echo "Cannot source configuration file: ${CSD_UCD_CONFIG}"
    installFailed
fi

#
# run DLAInstall for tal_csd_ucd
# source tal_common.config again
#
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV}


# Make sure config file exists and source it
if [ -r ${EUCOMM_WTSI_CONFIG} ]
then
    echo "Source ${EUCOMM_WTSI_CONFIG}"
    . ${EUCOMM_WTSI_CONFIG}
else
    echo "Cannot source configuration file: ${EUCOMM_WTSI_CONFIG}"
    installFailed
fi

#
# run DLAInstall for tal_csd_ucd
# source tal_common.config again
#
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV}


# Make sure config file exists and source it
if [ -r ${EUCOMM_WTSI_CONFIG} ]
then
    echo "Source ${EUCOMM_HGMU_CONFIG}"
    . ${EUCOMM_HGMU_CONFIG}
else
    echo "Cannot source configuration file: ${EUCOMM_HGMU_CONFIG}"
    installFailed
fi

#
# run DLAInstall for tal_csd_ucd
# source tal_common.config again
#
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV}

