#!/bin/sh

#
# Installation script
#
# 1) cp tal_common.config.default tal_common.config
# 2) cp tal_csd_mbp.config.default tal_csd_mbp.config
# 3) cp tal_csd_wtsi.config.default tal_csd_wtsi.config
# 4) cp tal_eucomm_wtsi.config.default tal_eucomm_wtsi.config
# 5) cp tal_eucomm_hgmu.config.default tal_eucomm_hgmu.config
# 6) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi


#
# Make sure config files exist
#
cd `dirname $0`

# establish the config file 
CSD_WTSI_CONFIG=tal_csd_wtsi.config
CSD_MBP_CONFIG=tal_csd_mbp.config
EUCOMM_WTSI_CONFIG=tal_eucomm_wtsi.config
EUCOMM_HMGU_CONFIG=tal_eucomm_hmgu.config
COMMON_CONFIG=tal_common.config

#
# Don't do the build for every config file.
#
DO_BUILD="-x"

# Make sure config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Create the input directory
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR} >/dev/null 2>&1
    if [ $? -eq 0 ]
    then
          echo "Directory created: ${INPUTDIR}"
    else
          echo "Cannot create directory: ${INPUTDIR}"
          installFailed
    fi
else
    echo "Directory already exists: ${INPUTDIR}"
fi

if [ "${DEV}" = "-d" ]
then
    chmod -f 775 ${INPUTDIR}
else
    chmod -f 755 ${INPUTDIR}
fi

echo 'running DLAINSTALL for each configuration of the load'

#########################################################################
# run DLAInstall for tal_csd_wtsi
#
if [ -r ${CSD_WTSI_CONFIG} ]
then
    echo "Source ${CSD_WTSI_CONFIG}"
    . ${CSD_WTSI_CONFIG}
else
    echo "Cannot source configuration file: ${CSD_WTSI_CONFIG}"
    installFailed
fi
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV} ${DO_BUILD}


#########################################################################
# run DLAInstall for tal_csd_mbp
#
if [ -r ${CSD_MBP_CONFIG} ]
then
    echo "Source ${CSD_MBP_CONFIG}"
    . ${CSD_MBP_CONFIG}
else
    echo "Cannot source configuration file: ${CSD_MBP_CONFIG}"
    installFailed
fi
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV} ${DO_BUILD}


#########################################################################
# run DLAInstall for tal_eucomm_wtsi
#
if [ -r ${EUCOMM_WTSI_CONFIG} ]
then
    echo "Source ${EUCOMM_WTSI_CONFIG}"
    . ${EUCOMM_WTSI_CONFIG}
else
    echo "Cannot source configuration file: ${EUCOMM_WTSI_CONFIG}"
    installFailed
fi
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV} ${DO_BUILD}


#########################################################################
# run DLAInstall for tal_eucomm_hmgu
#
if [ -r ${EUCOMM_HMGU_CONFIG} ]
then
    echo "Source ${EUCOMM_HMGU_CONFIG}"
    . ${EUCOMM_HMGU_CONFIG}
else
    echo "Cannot source configuration file: ${EUCOMM_HMGU_CONFIG}"
    installFailed
fi
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV} ${DO_BUILD}

#
# run DLAInstall for the last time, this time build the software
#
echo 'building the software'
DO_BUILD=""
. ${COMMON_CONFIG}
${DLAINSTALL} ${DEV} ${DO_BUILD}

