#!/bin/sh

#
# Installation script
#
# 1) cp tal_common.config.default tal_common.config
# 2) cp tal_regeneron.config.default tal_regeneron.config
# 3) cp tal_csd.config.default tal_csd.config
# 4) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config files
REGENERON_CONFIG=tal_regeneron.config
CSD_CONFIG=tal_csd.config
COMMON_CONFIG=tal_common.config

# Make sure config file exists and source it
if [ -r ${REGENERON_CONFIG} ]
then
    echo "Source ${REGENERON_CONFIG}"
    . ${REGENERON_CONFIG}
else
    echo "Cannot source configuration file: ${REGENERON_CONFIG}"
    installFailed
fi

# Make sure config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for each configuration file
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

# Make sure config file exists and source it
if [ -r ${CSD_CONFIG} ]
then
    echo "Source ${CSD_CONFIG}"
    . ${CSD_CONFIG}
else
    echo "Cannot source configuration file: ${CSD_CONFIG}"
    installFailed
fi

# cource tal_common.config again
. ${COMMON_CONFIG}

#
# run DLAInstall for tal_csd
#
${DLAINSTALL} ${DEV}

